# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

from __future__ import annotations

from .events import (
    EVENT_BASELINE_ABUSE,
    EVENT_BLAST_RADIUS,
    EVENT_CLAIM_COMPLETED,
    EVENT_CLAIM_VIOLATED,
    EVENT_INTENT_CHECKED,
    EVENT_INTENT_CLEARED,
    EVENT_INTENT_DECLARED,
    EVENT_INTENT_EXPANDED,
    EVENT_INTENT_EXPIRED,
    EVENT_INTENT_PROMOTED,
    EVENT_INTENT_QUEUE_BLOCKED,
    EVENT_INTENT_QUEUED,
    EVENT_INTENT_RENEWED,
    EVENT_INTENT_VIOLATED,
    EVENT_PATCH_BUDGET,
    EVENT_PATCH_EXPIRED,
    EVENT_PATCH_VERIFIED,
    EVENT_PATCH_VIOLATED,
    EVENT_RECEIPT_CREATED,
    EVENT_WORKSPACE_CONFLICT,
    EVENT_WORKSPACE_GC,
    AuditEvent,
    repo_root_digest,
)
from .validation import (
    DEFAULT_AUDIT_PATH,
    DEFAULT_AUDIT_PAYLOADS,
    DEFAULT_AUDIT_RETENTION_DAYS,
    DEFAULT_AUDIT_TOKEN_ESTIMATOR,
    AuditConfigError,
    AuditReadError,
    AuditSchemaError,
    AuditValidationError,
    resolve_audit_path,
    validate_payload_mode,
    validate_retention_days,
    validate_token_estimator,
)
from .writer import AuditWriter, NullAuditWriter, SqliteAuditWriter

__all__ = [
    "DEFAULT_AUDIT_PATH",
    "DEFAULT_AUDIT_PAYLOADS",
    "DEFAULT_AUDIT_RETENTION_DAYS",
    "DEFAULT_AUDIT_TOKEN_ESTIMATOR",
    "EVENT_BASELINE_ABUSE",
    "EVENT_BLAST_RADIUS",
    "EVENT_CLAIM_COMPLETED",
    "EVENT_CLAIM_VIOLATED",
    "EVENT_INTENT_CHECKED",
    "EVENT_INTENT_CLEARED",
    "EVENT_INTENT_DECLARED",
    "EVENT_INTENT_EXPANDED",
    "EVENT_INTENT_EXPIRED",
    "EVENT_INTENT_PROMOTED",
    "EVENT_INTENT_QUEUED",
    "EVENT_INTENT_QUEUE_BLOCKED",
    "EVENT_INTENT_RENEWED",
    "EVENT_INTENT_VIOLATED",
    "EVENT_PATCH_BUDGET",
    "EVENT_PATCH_EXPIRED",
    "EVENT_PATCH_VERIFIED",
    "EVENT_PATCH_VIOLATED",
    "EVENT_RECEIPT_CREATED",
    "EVENT_WORKSPACE_CONFLICT",
    "EVENT_WORKSPACE_GC",
    "AuditConfigError",
    "AuditEvent",
    "AuditReadError",
    "AuditSchemaError",
    "AuditValidationError",
    "AuditWriter",
    "NullAuditWriter",
    "SqliteAuditWriter",
    "repo_root_digest",
    "resolve_audit_path",
    "validate_payload_mode",
    "validate_retention_days",
    "validate_token_estimator",
]
