# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

"""Review receipt markdown and claims-not-made copy."""

from __future__ import annotations

from typing import Final

CLAIM_REASON_SECURITY_NOT_VULNERABILITY: Final = (
    "Security Surfaces are report-only trust-boundary inventory, "
    "not vulnerability claims."
)
CLAIM_REASON_BASELINE_DEBT_NOT_REGRESSION: Final = (
    "Known baseline debt was not treated as a new regression; "
    "novelty='known' remains baseline context."
)
CLAIM_REASON_REPORT_ONLY_NOT_CI_FAILURE: Final = (
    "Report-only signals were not treated as CI gate failures."
)
CLAIM_REASON_SUPPRESSED_CLONE_NOT_REGRESSION: Final = (
    "Suppressed clone groups were not counted as active new regressions."
)

DECISION_REASON_CLONE_DIVERGENCE: Final = (
    "Clone cohort member was in changed scope; confirm divergence is intentional."
)
DECISION_REASON_BASELINE_DEBT_TOUCHED: Final = (
    "Known baseline finding was in changed scope; confirm whether the patch "
    "addresses or preserves it."
)
DECISION_REASON_SCOPE_EXPANSION: Final = (
    "Edit scope expanded beyond declared files; human confirmation is required."
)

RECEIPT_MD_TITLE: Final = "## CodeClone Agent Review Receipt"
RECEIPT_MD_SECTION_SCOPE: Final = "### Scope"
RECEIPT_MD_SECTION_BLAST_RADIUS: Final = "### Blast Radius"
RECEIPT_MD_SECTION_REVIEWED_EVIDENCE: Final = "### Reviewed Evidence"
RECEIPT_MD_SECTION_PATCH_CONTRACT: Final = "### Patch Contract"
RECEIPT_MD_SECTION_STRUCTURAL_DELTA: Final = "### Structural Delta"
RECEIPT_MD_SECTION_HUMAN_DECISIONS: Final = "### Human Decisions Requested"
RECEIPT_MD_SECTION_CLAIMS_NOT_MADE: Final = "### Claims Not Made"
RECEIPT_MD_SECTION_VERIFICATION_PROFILE: Final = "### Verification Profile"
RECEIPT_MD_NO_INTENT: Final = "No intent declared."
RECEIPT_MD_NOT_AVAILABLE: Final = "Not available."
RECEIPT_MD_LIST_NONE: Final = "- none"
RECEIPT_MD_UNKNOWN: Final = "unknown"
RECEIPT_MD_NONE: Final = "none"
RECEIPT_MD_REVIEW_CONTRACT: Final = "**Review contract:** v1"
RECEIPT_MD_FOOTER: Final = "*Generated by CodeClone | run: `{run_id}` | {timestamp}*"
