# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

from __future__ import annotations

from typing import Final, Literal

MemoryBackend = Literal["sqlite", "postgres"]
MemoryMcpSyncPolicy = Literal["off", "bootstrap_if_missing", "refresh_when_stale"]
MemoryProjectionRebuildPolicy = Literal["off", "enqueue_when_stale"]
SemanticBackend = Literal["lancedb"]
SemanticEmbeddingProvider = Literal["diagnostic", "fastembed", "local_model", "api"]

DEFAULT_MEMORY_BACKEND: Final[MemoryBackend] = "sqlite"
DEFAULT_MEMORY_DB_PATH: Final = ".codeclone/memory/engineering_memory.sqlite3"
DEFAULT_MEMORY_ACTIVE_RETENTION_DAYS: Final = -1
DEFAULT_MEMORY_STALE_RETENTION_DAYS: Final = 180
DEFAULT_MEMORY_DRAFT_RETENTION_DAYS: Final = 14
DEFAULT_MEMORY_REJECTED_RETENTION_DAYS: Final = 30
DEFAULT_MEMORY_ARCHIVED_RETENTION_DAYS: Final = 365
DEFAULT_MEMORY_RECEIPT_RETENTION_DAYS: Final = 90
DEFAULT_MEMORY_MAX_RECORDS: Final = 10_000
DEFAULT_MEMORY_MAX_CANDIDATES: Final = 1_000
DEFAULT_MEMORY_MAX_EVIDENCE_PER_RECORD: Final = 20
DEFAULT_MEMORY_TARGET_STATEMENT_CHARS: Final = 300
DEFAULT_MEMORY_SOFT_STATEMENT_CHARS: Final = 500
DEFAULT_MEMORY_MAX_STATEMENT_CHARS: Final = 1_000
DEFAULT_MEMORY_STATEMENT_PREVIEW_CHARS: Final = 160
DEFAULT_MEMORY_MAX_BLAST_RADIUS_CACHE_ENTRIES: Final = 500
DEFAULT_MEMORY_GIT_HOTSPOT_PERIOD_DAYS: Final = 90
DEFAULT_MEMORY_GIT_HOTSPOT_MIN_CHANGES: Final = 5
DEFAULT_MEMORY_MCP_SYNC_POLICY: Final[MemoryMcpSyncPolicy] = "bootstrap_if_missing"
DEFAULT_MEMORY_TRAJECTORIES_ENABLED: Final = True
DEFAULT_MEMORY_TRAJECTORY_RETENTION_DAYS: Final = 365
DEFAULT_MEMORY_TRAJECTORY_EXPORT_ENABLED: Final = False
DEFAULT_MEMORY_TRAJECTORY_EXPORT_INCLUDE_PAYLOADS: Final = False
DEFAULT_MEMORY_TRAJECTORY_EXPORT_MAX_RECORD_BYTES: Final = 65_536
DEFAULT_MEMORY_TRAJECTORY_EXPORT_MAX_FILE_BYTES: Final = 10_485_760
DEFAULT_MEMORY_PROJECTION_REBUILD_POLICY: Final[MemoryProjectionRebuildPolicy] = "off"
DEFAULT_MEMORY_PROJECTION_REBUILD_RUNNING_TIMEOUT_SECONDS: Final = 1800
DEFAULT_MEMORY_PROJECTION_REBUILD_SPAWN_WORKER: Final = True

DEFAULT_INGEST_CONTRACT_CONSTANTS_PATHS: Final[tuple[str, ...]] = ()
DEFAULT_INGEST_DOCUMENT_LINK_PATHS: Final[tuple[str, ...]] = ()
DEFAULT_INGEST_MCP_TOOL_SCHEMA_SNAPSHOT_PATH: Final[str | None] = None
DEFAULT_INGEST_MCP_TOOL_COUNT_DOC_PATHS: Final[tuple[str, ...]] = ()

# Semantic retrieval index (Phase 20). Default OFF + "diagnostic" keep the
# community default zero-extra-dependency and offline; a real recall model is
# opt-in (fastembed/community local, api/paid later).
DEFAULT_SEMANTIC_ENABLED: Final = False
DEFAULT_SEMANTIC_BACKEND: Final[SemanticBackend] = "lancedb"
DEFAULT_SEMANTIC_INDEX_PATH: Final = ".codeclone/memory/semantic_index.lance"
DEFAULT_SEMANTIC_EMBEDDING_PROVIDER: Final[SemanticEmbeddingProvider] = "diagnostic"
DEFAULT_SEMANTIC_FASTEMBED_MODEL: Final = "BAAI/bge-small-en-v1.5"
DEFAULT_SEMANTIC_FASTEMBED_DIMENSION: Final = 384
DEFAULT_SEMANTIC_EMBEDDING_CACHE_DIR: Final = ".codeclone/memory/fastembed"
DEFAULT_SEMANTIC_ALLOW_MODEL_DOWNLOAD: Final = False
DEFAULT_SEMANTIC_DIMENSION: Final = 256
DEFAULT_SEMANTIC_MAX_RESULTS: Final = 20
DEFAULT_SEMANTIC_INDEX_AUDIT: Final = True

MEMORY_ENV_DB_PATH: Final = "CODECLONE_MEMORY_DB_PATH"
MEMORY_ENV_SEMANTIC_ENABLED: Final = "CODECLONE_MEMORY_SEMANTIC_ENABLED"
MEMORY_ENV_SEMANTIC_EMBEDDING_PROVIDER: Final = (
    "CODECLONE_MEMORY_SEMANTIC_EMBEDDING_PROVIDER"
)
MEMORY_ENV_SEMANTIC_EMBEDDING_MODEL: Final = "CODECLONE_MEMORY_SEMANTIC_EMBEDDING_MODEL"
MEMORY_ENV_SEMANTIC_EMBEDDING_CACHE_DIR: Final = (
    "CODECLONE_MEMORY_SEMANTIC_EMBEDDING_CACHE_DIR"
)
MEMORY_ENV_SEMANTIC_ALLOW_MODEL_DOWNLOAD: Final = (
    "CODECLONE_MEMORY_SEMANTIC_ALLOW_MODEL_DOWNLOAD"
)
MEMORY_ENV_SEMANTIC_INDEX_PATH: Final = "CODECLONE_MEMORY_SEMANTIC_INDEX_PATH"
MEMORY_ENV_PROJECTION_REBUILD_POLICY: Final = "CODECLONE_PROJECTION_REBUILD_POLICY"

__all__ = [
    "DEFAULT_INGEST_CONTRACT_CONSTANTS_PATHS",
    "DEFAULT_INGEST_DOCUMENT_LINK_PATHS",
    "DEFAULT_INGEST_MCP_TOOL_COUNT_DOC_PATHS",
    "DEFAULT_INGEST_MCP_TOOL_SCHEMA_SNAPSHOT_PATH",
    "DEFAULT_MEMORY_ACTIVE_RETENTION_DAYS",
    "DEFAULT_MEMORY_ARCHIVED_RETENTION_DAYS",
    "DEFAULT_MEMORY_BACKEND",
    "DEFAULT_MEMORY_DB_PATH",
    "DEFAULT_MEMORY_DRAFT_RETENTION_DAYS",
    "DEFAULT_MEMORY_GIT_HOTSPOT_MIN_CHANGES",
    "DEFAULT_MEMORY_GIT_HOTSPOT_PERIOD_DAYS",
    "DEFAULT_MEMORY_MAX_BLAST_RADIUS_CACHE_ENTRIES",
    "DEFAULT_MEMORY_MAX_CANDIDATES",
    "DEFAULT_MEMORY_MAX_EVIDENCE_PER_RECORD",
    "DEFAULT_MEMORY_MAX_RECORDS",
    "DEFAULT_MEMORY_MAX_STATEMENT_CHARS",
    "DEFAULT_MEMORY_MCP_SYNC_POLICY",
    "DEFAULT_MEMORY_PROJECTION_REBUILD_POLICY",
    "DEFAULT_MEMORY_PROJECTION_REBUILD_RUNNING_TIMEOUT_SECONDS",
    "DEFAULT_MEMORY_PROJECTION_REBUILD_SPAWN_WORKER",
    "DEFAULT_MEMORY_RECEIPT_RETENTION_DAYS",
    "DEFAULT_MEMORY_REJECTED_RETENTION_DAYS",
    "DEFAULT_MEMORY_SOFT_STATEMENT_CHARS",
    "DEFAULT_MEMORY_STALE_RETENTION_DAYS",
    "DEFAULT_MEMORY_STATEMENT_PREVIEW_CHARS",
    "DEFAULT_MEMORY_TARGET_STATEMENT_CHARS",
    "DEFAULT_MEMORY_TRAJECTORIES_ENABLED",
    "DEFAULT_MEMORY_TRAJECTORY_EXPORT_ENABLED",
    "DEFAULT_MEMORY_TRAJECTORY_EXPORT_INCLUDE_PAYLOADS",
    "DEFAULT_MEMORY_TRAJECTORY_EXPORT_MAX_FILE_BYTES",
    "DEFAULT_MEMORY_TRAJECTORY_EXPORT_MAX_RECORD_BYTES",
    "DEFAULT_MEMORY_TRAJECTORY_RETENTION_DAYS",
    "DEFAULT_SEMANTIC_ALLOW_MODEL_DOWNLOAD",
    "DEFAULT_SEMANTIC_BACKEND",
    "DEFAULT_SEMANTIC_DIMENSION",
    "DEFAULT_SEMANTIC_EMBEDDING_CACHE_DIR",
    "DEFAULT_SEMANTIC_EMBEDDING_PROVIDER",
    "DEFAULT_SEMANTIC_ENABLED",
    "DEFAULT_SEMANTIC_FASTEMBED_DIMENSION",
    "DEFAULT_SEMANTIC_FASTEMBED_MODEL",
    "DEFAULT_SEMANTIC_INDEX_AUDIT",
    "DEFAULT_SEMANTIC_INDEX_PATH",
    "DEFAULT_SEMANTIC_MAX_RESULTS",
    "MEMORY_ENV_DB_PATH",
    "MEMORY_ENV_PROJECTION_REBUILD_POLICY",
    "MEMORY_ENV_SEMANTIC_ALLOW_MODEL_DOWNLOAD",
    "MEMORY_ENV_SEMANTIC_EMBEDDING_CACHE_DIR",
    "MEMORY_ENV_SEMANTIC_EMBEDDING_MODEL",
    "MEMORY_ENV_SEMANTIC_EMBEDDING_PROVIDER",
    "MEMORY_ENV_SEMANTIC_ENABLED",
    "MEMORY_ENV_SEMANTIC_INDEX_PATH",
    "MemoryBackend",
    "MemoryMcpSyncPolicy",
    "MemoryProjectionRebuildPolicy",
    "SemanticBackend",
    "SemanticEmbeddingProvider",
]
