# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

from __future__ import annotations

from typing import Final, Literal

MemoryBackend = Literal["sqlite", "postgres"]
MemoryMcpSyncPolicy = Literal["off", "bootstrap_if_missing", "refresh_when_stale"]

DEFAULT_MEMORY_BACKEND: Final[MemoryBackend] = "sqlite"
DEFAULT_MEMORY_DB_PATH: Final = ".cache/codeclone/memory/engineering_memory.sqlite3"
DEFAULT_MEMORY_ACTIVE_RETENTION_DAYS: Final = -1
DEFAULT_MEMORY_STALE_RETENTION_DAYS: Final = 180
DEFAULT_MEMORY_DRAFT_RETENTION_DAYS: Final = 14
DEFAULT_MEMORY_REJECTED_RETENTION_DAYS: Final = 30
DEFAULT_MEMORY_ARCHIVED_RETENTION_DAYS: Final = 365
DEFAULT_MEMORY_RECEIPT_RETENTION_DAYS: Final = 90
DEFAULT_MEMORY_MAX_RECORDS: Final = 10_000
DEFAULT_MEMORY_MAX_CANDIDATES: Final = 1_000
DEFAULT_MEMORY_MAX_EVIDENCE_PER_RECORD: Final = 20
DEFAULT_MEMORY_MAX_STATEMENT_CHARS: Final = 2_000
DEFAULT_MEMORY_MAX_BLAST_RADIUS_CACHE_ENTRIES: Final = 500
DEFAULT_MEMORY_GIT_HOTSPOT_PERIOD_DAYS: Final = 90
DEFAULT_MEMORY_GIT_HOTSPOT_MIN_CHANGES: Final = 5
DEFAULT_MEMORY_MCP_SYNC_POLICY: Final[MemoryMcpSyncPolicy] = "bootstrap_if_missing"

MEMORY_ENV_DB_PATH: Final = "CODECLONE_MEMORY_DB_PATH"

__all__ = [
    "DEFAULT_MEMORY_ACTIVE_RETENTION_DAYS",
    "DEFAULT_MEMORY_ARCHIVED_RETENTION_DAYS",
    "DEFAULT_MEMORY_BACKEND",
    "DEFAULT_MEMORY_DB_PATH",
    "DEFAULT_MEMORY_DRAFT_RETENTION_DAYS",
    "DEFAULT_MEMORY_GIT_HOTSPOT_MIN_CHANGES",
    "DEFAULT_MEMORY_GIT_HOTSPOT_PERIOD_DAYS",
    "DEFAULT_MEMORY_MAX_BLAST_RADIUS_CACHE_ENTRIES",
    "DEFAULT_MEMORY_MAX_CANDIDATES",
    "DEFAULT_MEMORY_MAX_EVIDENCE_PER_RECORD",
    "DEFAULT_MEMORY_MAX_RECORDS",
    "DEFAULT_MEMORY_MAX_STATEMENT_CHARS",
    "DEFAULT_MEMORY_MCP_SYNC_POLICY",
    "DEFAULT_MEMORY_RECEIPT_RETENTION_DAYS",
    "DEFAULT_MEMORY_REJECTED_RETENTION_DAYS",
    "DEFAULT_MEMORY_STALE_RETENTION_DAYS",
    "MEMORY_ENV_DB_PATH",
    "MemoryBackend",
    "MemoryMcpSyncPolicy",
]
