# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

"""Canonical normalized model (F-3): one semantic model, two representations.

Frozen semantic substrate of the run-store backend (a2 wave 1).  The four
architecture walls hold here by construction: cache is never truth, a run is
never a previous run plus a patch, storage identifiers never escape into the
wire, and the normalized wire is never the expanded legacy object.
"""

from codeclone.canonical.authority_identity import (
    CANDIDATE_IDENTITY_CONTRACT,
    VIOLATION_IDENTITY_CONTRACT,
    candidate_handle,
    candidate_total_order_key,
    legacy_symbol_key,
    violation_handle,
)
from codeclone.canonical.codec import (
    canonical_float_lexeme,
    canonical_string_lexeme,
    decode_canonical_json,
    encode_canonical_json,
)
from codeclone.canonical.errors import (
    CanonicalModelError,
    ExportIntegrityError,
    LegacyIngestError,
    RunStoreError,
    StoreCompatibilityError,
    StoreFenceError,
    StoreIntegrityError,
    UnknownRunError,
    WireDecodeError,
)
from codeclone.canonical.export import (
    ByteSink,
    ExportEnvelope,
    WitnessLayer,
    canonical_artifact_digest,
    verify_export_artifact,
)
from codeclone.canonical.identity import (
    DEPENDENCY_BINDINGS,
    EFFECT_KINDS,
    IMPORT_TYPES,
    OPERATION_KINDS,
    VIOLATION_KINDS,
    AnalysisFile,
    DependencyEndpoint,
    EffectLabelRoot,
    EffectRoot,
    FileId,
    KnownModule,
    ModuleId,
    OpaqueDottedHead,
    OperationHead,
    OperationRoot,
    OperationTarget,
    ProducerRoot,
    SymbolId,
    UnresolvedRoot,
    canonical_key,
    endpoint_key,
    head_tag,
    root_family,
)
from codeclone.canonical.ingest import canonical_model_from_legacy_document
from codeclone.canonical.model import (
    AnalysisFacts,
    CandidateRow,
    CanonicalFacts,
    CanonicalModel,
    ComparisonFacts,
    ContractRow,
    DependencyEdgeRow,
    EvaluationFacts,
    FileModuleRelation,
    GraphNodeRow,
    SemanticEdge,
    SinkRoleRow,
    ViolationRow,
)
from codeclone.canonical.registry import (
    FACT_FAMILY_FIELDS,
    FieldDeclaration,
    derived_wire_columns,
    sparse_bool_wire_columns,
    wire_columns,
    wire_fact_family_order,
)
from codeclone.canonical.store import (
    HeadState,
    PublishReceipt,
    RunStore,
    analysis_scope_digest,
    export_head,
    export_run,
)

__all__ = [
    "CANDIDATE_IDENTITY_CONTRACT",
    "DEPENDENCY_BINDINGS",
    "EFFECT_KINDS",
    "FACT_FAMILY_FIELDS",
    "IMPORT_TYPES",
    "OPERATION_KINDS",
    "VIOLATION_IDENTITY_CONTRACT",
    "VIOLATION_KINDS",
    "AnalysisFacts",
    "AnalysisFile",
    "ByteSink",
    "CandidateRow",
    "CanonicalFacts",
    "CanonicalModel",
    "CanonicalModelError",
    "ComparisonFacts",
    "ContractRow",
    "DependencyEdgeRow",
    "DependencyEndpoint",
    "EffectLabelRoot",
    "EffectRoot",
    "EvaluationFacts",
    "ExportEnvelope",
    "ExportIntegrityError",
    "FieldDeclaration",
    "FileId",
    "FileModuleRelation",
    "GraphNodeRow",
    "HeadState",
    "KnownModule",
    "LegacyIngestError",
    "ModuleId",
    "OpaqueDottedHead",
    "OperationHead",
    "OperationRoot",
    "OperationTarget",
    "ProducerRoot",
    "PublishReceipt",
    "RunStore",
    "RunStoreError",
    "SemanticEdge",
    "SinkRoleRow",
    "StoreCompatibilityError",
    "StoreFenceError",
    "StoreIntegrityError",
    "SymbolId",
    "UnknownRunError",
    "UnresolvedRoot",
    "ViolationRow",
    "WireDecodeError",
    "WitnessLayer",
    "analysis_scope_digest",
    "candidate_handle",
    "candidate_total_order_key",
    "canonical_artifact_digest",
    "canonical_float_lexeme",
    "canonical_key",
    "canonical_model_from_legacy_document",
    "canonical_string_lexeme",
    "decode_canonical_json",
    "derived_wire_columns",
    "encode_canonical_json",
    "endpoint_key",
    "export_head",
    "export_run",
    "head_tag",
    "legacy_symbol_key",
    "root_family",
    "sparse_bool_wire_columns",
    "verify_export_artifact",
    "violation_handle",
    "wire_columns",
    "wire_fact_family_order",
]
