# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

"""Closed vocabulary for bounded Platform Observability telemetry."""

from __future__ import annotations

from typing import Final

from ..contracts import OBSERVER_VOCABULARY_VERSION

DB_COUNTER_VERSION: Final = 2

_MCP_TOOL_NAMES: Final = frozenset(
    {
        "analyze_changed_paths",
        "analyze_repository",
        "check_clones",
        "check_cohesion",
        "check_complexity",
        "check_coupling",
        "check_dead_code",
        "check_patch_contract",
        "clear_session_runs",
        "compare_runs",
        "create_review_receipt",
        "evaluate_gates",
        "finish_controlled_change",
        "generate_pr_summary",
        "get_blast_artifact",
        "get_blast_radius",
        "get_controller_audit_trail",
        "get_finding",
        "get_implementation_context",
        "get_implementation_context_page",
        "get_memory_projection_page",
        "get_patch_trail",
        "get_production_triage",
        "get_relevant_memory",
        "get_remediation",
        "get_report_section",
        "get_review_receipt",
        "get_run_summary",
        "get_workspace_session_stats",
        "help",
        "list_findings",
        "list_hotspots",
        "list_reviewed_findings",
        "manage_change_intent",
        "manage_engineering_memory",
        "mark_finding_reviewed",
        "query_engineering_memory",
        "query_platform_observability",
        "start_controlled_change",
        "validate_review_claims",
    }
)

SPAN_NAMES: Final[frozenset[str]] = frozenset(
    {
        "analytics.build",
        "analytics.cluster",
        "analytics.embed",
        "analytics.report",
        "analytics.snapshot",
        "analysis.registry_bind",
        "analysis.relative_imports",
        "audit.digest_link",
        "baseline.container.build",
        "baseline.container.publish",
        "baseline.container.read",
        "baseline.container.trust",
        "cache.backend.activate_generation",
        "cache.backend.load_generation",
        "cache.backend.prune",
        "cache.backend.write_generation",
        "cache.content_identity",
        "cache.decode_entries",
        "cache.profile_reuse",
        "cache.read_json",
        "cache.release_entries",
        "cache.segment_projection",
        "cache.stat",
        "cache.validate_envelope",
        "compatibility.check",
        "config.resolve",
        "controller.registry_bind",
        "hygiene.collect_dirty_paths",
        "hygiene.collect_dirty_snapshot",
        "hygiene.dirty_entry_digests",
        "hygiene.git.rev_parse",
        "hygiene.git.status",
        "manifest.build",
        "memory.embedding.documents",
        "memory.embedding.infer",
        "memory.embedding.model_load",
        "memory.embedding.query",
        "memory.experience.distill",
        "memory.identity.migrate",
        "memory.retrieval.merge",
        "memory.semantic.bootstrap",
        "memory.semantic.embed",
        "memory.semantic.rebuild",
        "memory.semantic.reconcile",
        "memory.semantic.search",
        "memory.semantic.source.audit",
        "memory.semantic.source.memory",
        "memory.semantic.source.trajectory",
        "memory.subject.resolve",
        "memory.trajectory.rebuild",
        "memory.projection.worker_bootstrap",
        "observations.build",
        "observations.lanes.build",
        "pipeline.analyze",
        "pipeline.baseline",
        "pipeline.bootstrap",
        "pipeline.cache_load",
        "pipeline.discover",
        "pipeline.process",
        "pipeline.report",
        "registry.build",
        "release.phase39.matrix",
        "report.build",
        "report.evaluate",
        "report.finalize",
        "report.html.context",
        "report.html.sections",
        "report.html.styles",
        "report.render",
        "retrieval.embed_query",
        "semantics.authority.build",
        "semantics.events",
        "semantics.flow",
        "mcp.run_store.register",
        "mcp.run_store.resolve_artifact",
        *(f"mcp.{name}" for name in _MCP_TOOL_NAMES),
    }
)

COUNTER_KEYS: Final[frozenset[str]] = frozenset(
    {
        "audit.emit_dropped",
        "batch",
        "batches",
        "cache_entries",
        "cache_file_bytes",
        "cache_hits",
        "chars",
        "count",
        "db_queries",
        "db_rows",
        "db_writes",
        "decoded_entries",
        "deleted",
        "dirty_entries",
        "dirty_paths",
        "documents",
        "embedded",
        "embedding_batch_size",
        "embedding_dimensions",
        "embedding_max_padded_tokens",
        "experiences_distilled",
        "failed_files",
        "files_analyzed",
        "files_to_process",
        "git_diff_invocations",
        "html_css_chars",
        "html_js_chars",
        "html_section_chars",
        "html_sections_rendered",
        "indexed",
        "lane_audit",
        "lane_memory",
        "lane_trajectory",
        "max_chars",
        "max_documents",
        "max_padded_tokens",
        "max_tokens",
        "memory.propose_candidate_dropped",
        "padded_tokens",
        "padding_amplification_permille",
        "pending",
        "phase_class_metrics_us",
        "phase_dead_code_us",
        "phase_module_bindings_us",
        "phase_module_passes_us",
        "phase_module_walk_us",
        "phase_parse_us",
        "phase_qualname_us",
        "phase_relationship_us",
        "phase_suppressions_us",
        "phase_unit_blocks_us",
        "phase_unit_cfg_us",
        "phase_unit_normalize_cfg_us",
        "phase_unit_normalize_stmt_us",
        "phase_unit_segments_us",
        "phase_unit_structural_us",
        "released_entries",
        "retrieval.fts_hits",
        "retrieval.fts_vector_overlap",
        "retrieval.semantic_filtered",
        "retrieval.vector_audit_hits",
        "retrieval.vector_memory_hits",
        "retrieval.vector_trajectory_hits",
        "skipped_unchanged",
        "spans_dropped",
        "subphase_module_passes_adoption_us",
        "subphase_module_passes_reachability_binding_us",
        "subphase_module_passes_reachability_visit_us",
        "subphase_module_passes_security_us",
        "total_chars",
        "total_tokens",
        "untracked_file_reads",
        "workflows_seen",
        # Phase 39 aggregate vocabulary. Enum-valued outcomes are represented
        # as one fixed key per closed value by their owning slice.
        "analysis_dependency_targets",
        "analysis_inventory_submodule_expansions",
        "analysis_known_internal_not_analyzed",
        "candidates_emitted",
        "cache_backend_changed_entries",
        "cache_backend_contention",
        "cache_backend_entries",
        "cache_backend_orphans",
        "cache_backend_pruned",
        "cache_backend_read_bytes",
        "cache_backend_recovery_corrupt",
        "cache_backend_recovery_current",
        "cache_backend_recovery_previous",
        "cache_backend_removed_entries",
        "cache_backend_write_bytes",
        "cache_content_decision_blob_hit",
        "cache_content_decision_digest_hit",
        "cache_content_decision_digest_miss",
        "cache_content_decision_dirty",
        "cache_content_decision_git_unavailable",
        "cache_content_decision_index_ambiguous",
        "cache_content_decision_racy",
        "cache_content_decision_untracked",
        "cache_content_digest_verify_cost_us",
        "cache_lane_dependent_miss",
        "cache_lane_neutral_hit",
        "cache_profile_hit",
        "cache_profile_miss",
        "cache_stat_fast_reject",
        "compatibility_status_compatible",
        "compatibility_status_incompatible",
        "compatibility_status_migration_required",
        "compatibility_status_unknown_contract",
        "config_autodetect_used",
        "config_configured_roots",
        "config_validation_failures",
        "contract_count",
        "controller_registry_bindings",
        "events_by_kind.artifact_write",
        "events_by_kind.assign",
        "events_by_kind.compatibility_check",
        "events_by_kind.compute_digest",
        "events_by_kind.construct",
        "events_by_kind.field_write",
        "events_by_kind.publish_event",
        "events_by_kind.resolve_identity",
        "events_by_kind.return_value",
        "events_by_kind.serialize_field",
        "events_by_kind.security_observation",
        "events_unresolved",
        "facts_bound",
        "manifest_collisions",
        "manifest_input_files",
        "manifest_mounts",
        "manifest_null_modules",
        "manifest_portability_failures",
        "manifest_resolved_modules",
        "memory_fts_candidates",
        "memory_invalidated_jobs",
        "memory_jobs_coalesced",
        "memory_migration_failed",
        "memory_migration_migrated",
        "memory_migration_noop",
        "memory_subjects_mapped",
        "memory_subjects_unchanged",
        "memory_subjects_unresolved",
        "memory_unique_record_ids",
        "memory_vector_candidates",
        "memory_vector_fts_overlap",
        "observations_contract_failures",
        "observations_enabled_lanes",
        "observations_fact_families",
        "observations_lane_bytes",
        "observations_lane_items",
        "observations_semantic_reuse",
        "registry_analyzed",
        "registry_collisions",
        "registry_discovered",
        "registry_hard_excluded",
        "registry_inventoried",
        "registry_known_internal_not_analyzed",
        "registry_null_modules",
        "registry_worker_installs",
        "release_bytes",
        "release_duration_ms",
        "release_failed",
        "release_passed",
        "release_rss_mb",
        "release_scenarios",
        "release_sql_statements",
        "report_gate_fail",
        "report_gate_pass",
        "report_items",
        "report_novelty_known",
        "report_novelty_new",
        "report_novelty_unavailable",
        "report_render_bytes",
        "report_render_format_html",
        "report_render_format_json",
        "report_render_format_markdown",
        "report_render_format_sarif",
        "report_render_format_text",
        "report_trust_trusted",
        "report_trust_untrusted",
        "run_store_artifact_bytes",
        "run_store_artifacts_drifted",
        "run_store_artifacts_missing",
        "run_store_artifacts_retained",
        "run_store_evaluations_evicted",
        "run_store_evaluations_retained",
        "run_store_expired",
        "run_store_runs_evicted",
        "run_store_runs_retained",
        "run_store_selector_hits",
        "run_store_selector_misses",
        "audit_digest_links",
        "baseline_bytes",
        "baseline_compatibility_fail",
        "baseline_compatibility_pass",
        "baseline_items",
        "baseline_lanes",
        "baseline_publish_backups",
        "baseline_publish_bytes",
        "baseline_publish_conflict",
        "baseline_publish_failure",
        "baseline_publish_fsyncs",
        "baseline_publish_lanes",
        "baseline_publish_noop",
        "baseline_publish_recovered",
        "baseline_publish_replaced",
        "baseline_publish_transitions",
        "baseline_root_verification_fail",
        "baseline_root_verification_pass",
        "baseline_lane_verification_fail",
        "baseline_lane_verification_pass",
        "baseline_read_failures",
        "files_timed",
        "files_discovered",
        "files_inventoried",
        "fixpoint_iterations",
        "functions_summarized",
        "ir_nodes",
        "scc_count",
        "sinks_by_status.adapter",
        "sinks_by_status.authoritative",
        "sinks_by_status.mixed",
        "sinks_by_status.shadow",
        "sinks_by_status.unavailable",
        "typed_failures",
        "units_eligible",
        "units_fingerprinted",
        "units_seen",
        "unresolved_flow_functions",
        "unresolved_relatives",
        "blocks_emitted",
        "segments_emitted",
    }
)


class ObservabilityVocabularyError(ValueError):
    """A span name or counter key is outside the reviewed vocabulary."""


def validate_span_name(name: str) -> str:
    if name not in SPAN_NAMES:
        raise ObservabilityVocabularyError(
            f"unknown observability span name {name!r}; update the reviewed vocabulary"
        )
    return name


def validate_counter_key(key: str) -> str:
    if key not in COUNTER_KEYS:
        raise ObservabilityVocabularyError(
            f"unknown observability counter key {key!r}; update the reviewed vocabulary"
        )
    return key


__all__ = [
    "COUNTER_KEYS",
    "DB_COUNTER_VERSION",
    "OBSERVER_VOCABULARY_VERSION",
    "SPAN_NAMES",
    "ObservabilityVocabularyError",
    "validate_counter_key",
    "validate_span_name",
]
