# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

from __future__ import annotations

from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from typing import Protocol

from .models import (
    IngestionRun,
    MemoryEvidence,
    MemoryLink,
    MemoryProject,
    MemoryQuery,
    MemoryRecord,
    MemoryRevision,
    MemorySubject,
    RecordBatch,
    UpsertResult,
)


class EngineeringMemoryStore(Protocol):
    def initialize(self, project: MemoryProject) -> None: ...
    def get_meta(self, key: str) -> str | None: ...
    def set_meta(self, key: str, value: str) -> None: ...
    def write_record(self, record: MemoryRecord) -> None: ...
    def upsert_record(self, record: MemoryRecord) -> UpsertResult: ...
    def find_record(self, record_id: str) -> MemoryRecord | None: ...
    def find_by_identity_key(
        self, project_id: str, key: str
    ) -> MemoryRecord | None: ...
    def query_records(self, query: MemoryQuery) -> Sequence[MemoryRecord]: ...
    def write_subject(self, subject: MemorySubject) -> None: ...
    def write_evidence(self, evidence: MemoryEvidence) -> None: ...
    def write_link(self, link: MemoryLink) -> None: ...
    def write_ingestion_run(self, run: IngestionRun) -> None: ...
    def write_revision(self, revision: MemoryRevision) -> None: ...
    def mark_stale(self, record_id: str, reason: str) -> None: ...
    def persist_batch(self, batch: RecordBatch) -> dict[str, int]: ...
    def close(self) -> None: ...

    @contextmanager
    def transaction(self) -> Iterator[None]: ...

    @contextmanager
    def exclusive_init_lock(self) -> Iterator[None]: ...


__all__ = ["EngineeringMemoryStore"]
