# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Den Rozhnovskiy

"""Markdown report projection copy."""

from __future__ import annotations

from typing import Final

from ...domain.findings import (
    FAMILY_CLONE,
    FAMILY_DEAD_CODE,
    FAMILY_STRUCTURAL,
)
from .projections import MD_TITLE, PROJECTION_NONE

MD_SCHEMA_LABEL: Final = "Markdown schema"
MD_SOURCE_SCHEMA_LABEL: Final = "Source report schema"
MD_PROJECT_LABEL: Final = "Project"
MD_ANALYSIS_MODE_LABEL: Final = "Analysis mode"
MD_REPORT_MODE_LABEL: Final = "Report mode"
MD_GENERATED_BY_LABEL: Final = "Generated by"
MD_PYTHON_LABEL: Final = "Python"
MD_REPORT_GENERATED_LABEL: Final = "Report generated (UTC)"

MD_LABEL_HEALTH: Final = "Health"
MD_LABEL_TOTAL_FINDINGS: Final = "Total findings"
MD_LABEL_FAMILIES: Final = "Families"
MD_LABEL_STRONGEST_DIMENSION: Final = "Strongest dimension"
MD_LABEL_WEAKEST_DIMENSION: Final = "Weakest dimension"
MD_LABEL_FILES: Final = "Files"
MD_LABEL_CODE: Final = "Code"
MD_LABEL_TOTAL: Final = "Total"
MD_LABEL_BY_FAMILY: Final = "By family"
MD_LABEL_BY_SEVERITY: Final = "By severity"
MD_LABEL_BY_IMPACT_SCOPE: Final = "By impact scope"
MD_LABEL_SOURCE_SCOPE: Final = "Source scope breakdown"

MD_FINDING_ID: Final = "Finding ID"
MD_FAMILY: Final = "Family"
MD_CATEGORY: Final = "Category"
MD_KIND: Final = "Kind"
MD_SEVERITY: Final = "Severity"
MD_CONFIDENCE: Final = "Confidence"
MD_PRIORITY: Final = "Priority"
MD_SCOPE: Final = "Scope"
MD_SPREAD: Final = "Spread"
MD_OCCURRENCES: Final = "Occurrences"
MD_FACTS: Final = "Facts"
MD_PRESENTATION_FACTS: Final = "Presentation facts"
MD_LOCATIONS: Final = "Locations"
MD_MORE_OCCURRENCES: Final = "... and {count} more occurrence(s)"

MD_NONE: Final = "_None._"
MD_SUPPRESSED_CLONE_GROUP: Final = "Suppressed clone group"

MD_HEADING_CLONE: Final = "{category} clone group{suffix}"
MD_HEADING_STRUCTURAL: Final = "Structural finding: {category}"
MD_HEADING_DEAD_CODE: Final = "Dead code: {category}"
MD_HEADING_DESIGN: Final = "Design finding: {category}"

MD_ANCHORS: Final[tuple[tuple[str, str, int], ...]] = (
    ("overview", "Overview", 2),
    ("inventory", "Inventory", 2),
    ("findings-summary", "Findings Summary", 2),
    ("top-risks", "Top Risks", 2),
    ("suggestions", "Suggestions", 2),
    ("findings", "Findings", 2),
    ("clone-findings", "Clone Findings", 3),
    ("structural-findings", "Structural Findings", 3),
    ("dead-code-findings", "Dead Code Findings", 3),
    ("design-findings", "Design Findings", 3),
    ("metrics", "Metrics", 2),
    ("health", "Health", 3),
    ("complexity", "Complexity", 3),
    ("coupling", "Coupling", 3),
    ("cohesion", "Cohesion", 3),
    ("coverage-join", "Coverage Join", 3),
    ("overloaded-modules", "Overloaded Modules", 3),
    ("dependencies", "Dependencies", 3),
    ("dead-code-metrics", "Dead Code", 3),
    ("dead-code-suppressed", "Suppressed Dead Code", 3),
    ("integrity", "Integrity", 2),
)


def finding_heading(*, family: str, category: str, clone_type: str = "") -> str:
    category_text = category.title() if category else category
    if family == FAMILY_CLONE:
        suffix = f" ({clone_type})" if clone_type else ""
        return MD_HEADING_CLONE.format(category=category_text, suffix=suffix)
    if family == FAMILY_STRUCTURAL:
        return MD_HEADING_STRUCTURAL.format(category=category)
    if family == FAMILY_DEAD_CODE:
        return MD_HEADING_DEAD_CODE.format(category=category)
    return MD_HEADING_DESIGN.format(category=category)


def projection_none() -> str:
    return PROJECTION_NONE


__all__ = [
    "MD_ANCHORS",
    "MD_TITLE",
    "finding_heading",
    "projection_none",
]
